server:
  port: 8090

spring:
  application:
    name: springboot-oracle
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    lettuce:
      pool:
        maxActive: 8
        maxIdle: 100
        minIdle: 10
        maxWait: -1
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    #url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: yang
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 10
      maximumPoolSize: 200
      autoCommit: true
      idleTimeout: 30000
      poolName: MasterDatabookHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000
  thymeleaf:
    #默认开启Thymeleaf 的缓存，开发环境需要关闭，不然在开发过程中修改页面不会立刻生效需要重启
    cache: false
    #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
#mybatis+配置
mybatis-plus:
  mapper-locations: classpath*:example/demo/mapper/*Mapper.xml
  type-aliases-package: example.demo.entity
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      db-type: oracle
#控制台日志
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    example:
      demo: debug